name: "dbt_ngpvan"
version: "1.0.0"
config-version: 2

profile: "dbt_ngpvan"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["documentation_blocks"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_ngpvan:
    base:
      +schema: "{{ 'base' if 'prod' in target.name else 'dev' }}"
      +materialized: table
    staging:
      +schema: "{{ 'staging' if 'prod' in target.name else 'dev' }}"
      +materialized: table
    intermediate:
      +schema: "{{ 'intermediate' if 'prod' in target.name else 'dev' }}"
      +materialized: table

tests:
  +severity: warn # all tests

vars:
  raw_database_name: tmc-data-warehouse
  dbt_ngpvan_config:
    vendor_name: ngpvan
    source_database: tmc-data-warehouse
    schema_list:
      - raw_avvan__ngpvan_corrected
      - raw_svvan__corrected
      - raw_smartvan
    table_logic: pattern
    table_exclude_list:
      # these tables are EveryAction
      # raw_bonterra include _vf versions of these tables which will be pulled in
      - codes
      - contactsactivistcodes
      - contactscodes
      - contactscontacts
      - contactsnotes_myc
      - contactsnotes_mym
      - contactssurveyresponses
      # This is a voter registration table that we'll model separately
      - contactscontacts_vr
    packages:
      core:
        enabled: true
      myvoters:
        enabled: true
      digital:
        enabled: false
      ngp:
        enabled: false
      basic_dev:
        enabled: false
      standard_dev:
        enabled: false
      pro_dev:
        enabled: false
      ea360:
        enabled: false
    add_ons: []
    segmentation: true
    lookup_tables: true
    additional_fields:
      - _avvan_source_relation
    ngpvan_default_incremental_window_days: 3