name: 'dbt_van'
version: '1.0.0'
config-version: 2

profile: 'dbt_van'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_van:
    base:
      +schema: "{{ 'base' if 'prod' in target.name else 'dev' }}"
      +materialized: table
    staging:
      +schema: "{{ 'staging' if 'prod' in target.name else 'dev' }}"
      +materialized: table

tests:
  +severity: warn  # all tests

vars:
  dbt_ngpvan_config:
    vendor_name: ngpvan
    schema_list: [raw_van, raw_van__tmc]
    table_logic: pattern
    packages:
      core:
        enabled: true
      myvoters:
        enabled: true
      digital:
        enabled: false
      ngp:
        enabled: false
      basic_dev:
        enabled: false
      standard_dev:
        enabled: false
      pro_dev:
        enabled: false
      ea360:
        enabled: false
    add_ons: []
    segmentation: true
    lookup_tables: true