name: 'dbt_van'
version: '1.0.0'
config-version: 2

profile: 'dbt_van'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_van:
    base:
      +schema: dbt_base
      +materialized: table
    staging:
      +schema: dbt_staging
      +materialized: table

tests:
  +severity: warn  # all tests

vars:
  vendors:
    van:
      - schema: None
        tables:
          activistcodes:
            - name: activistcodes
          codes:
            - name: codes
          codetypes:
            - name: codetypes
          committees:
            - name: committees
          contactsactivistcodes:
            - name: contactsactivistcodes
          contactscodes:
            - name: contactscodes
          contactscontacts:
            - name: contactscontacts
          contactsnotes:
            - name: contactsnotes
          contactssurveyresponses:
            - name: contactssurveyresponses
          contacttypes:
            - name: contacttypes
          inputtypes:
            - name: inputtypes
          surveyquestions:
            - name: surveyquestions
          surveyresponses:
            - name: surveyresponses
          users:
            - name: usersusergroups
          usersusergroups:
            - name: usersusergroups