name: 'dbt_van'
version: '1.0.0'
config-version: 2

profile: 'dbt_van'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_van:
    base:
      +schema: "{{ 'base' if 'prod' in target.name else 'dev' }}"
      +materialized: table
    staging:
      +schema: "{{ 'staging' if 'prod' in target.name else 'dev' }}"
      +materialized: table

tests:
  +severity: warn  # all tests

vars:
  dbt_van_config:
    schema_list: []
    table_logic: pattern