dbt_van:
  target: dev
  outputs:
    rs_dev:
      dbname: '{{ env_var(''DEV_REDSHIFT_USER_DATABASE'') }}'
      host: '{{ env_var(''DEV_REDSHIFT_USER_HOST'') }}'
      password: '{{ env_var(''DEV_REDSHIFT_USER_CREDENTIAL_PASSWORD'') }}'
      port: '{{ env_var(''DEV_REDSHIFT_USER_PORT'') | as_number }}'
      schema: '{{ ''dbt_'' + env_var(''DEV_REDSHIFT_USER_CREDENTIAL_USERNAME'') + ''_dev'' }}'
      threads: 4
      type: redshift
      user: '{{ env_var(''DEV_REDSHIFT_USER_CREDENTIAL_USERNAME'') }}'
      connect_timeout: 999999
    rs_prod:
      dbname: '{{ env_var(''PROD_REDSHIFT_USER_DATABASE'') }}'
      host: '{{ env_var(''PROD_REDSHIFT_USER_HOST'') }}'
      password: '{{ env_var(''PROD_REDSHIFT_USER_CREDENTIAL_PASSWORD'') }}'
      port: '{{ env_var(''PROD_REDSHIFT_USER_PORT'') | as_number }}'
      schema: prod
      threads: 4
      type: redshift
      user: '{{ env_var(''PROD_REDSHIFT_USER_CREDENTIAL_USERNAME'') }}'
      connect_timeout: 999999
    dev:
      type: bigquery
      method: service-account
      keyfile: ./service_accounts/tmc-dev-394022-b3cd7a44d0c2.json
      project: tmc-dev-394022
      dataset: '{{ ''dbt_'' + env_var(''DEV_SCHEMA_NAME'') }}'
      threads: 4
      location: us-central1
    prod:
      type: bigquery
      method: service-account
      keyfile: ./service_accounts/tmc-data-warehouse-6cd730dc34db.json
      project: tmc-data-warehouse
      dataset: prod
      threads: 4
      location: us-central1
