{% macro normalize_state_code(state) -%}

    CASE
        WHEN TRIM(UPPER({{ state }})) IN ('ALABAMA', 'AL') THEN 'AL' 
        WHEN TRIM(UPPER({{ state }})) IN ('ALASKA', 'AK') THEN 'AK' 
        WHEN TRIM(UPPER({{ state }})) IN ('ARIZONA', 'AZ') THEN 'AZ' 
        WHEN TRIM(UPPER({{ state }})) IN ('ARKANSAS', 'AR') THEN 'AR' 
        WHEN TRIM(UPPER({{ state }})) IN ('CALIFORNIA', 'CA') THEN 'CA' 
        WHEN TRIM(UPPER({{ state }})) IN ('COLORADO', 'CO') THEN 'CO' 
        WHEN TRIM(UPPER({{ state }})) IN ('CONNECTICUT', 'CT') THEN 'CT' 
        WHEN TRIM(UPPER({{ state }})) IN ('DELEWARE', 'DE') THEN 'DE' 
        WHEN TRIM(UPPER({{ state }})) IN ('DISTRICT OF COLUMBIA', 'DC') THEN 'DC' 
        WHEN TRIM(UPPER({{ state }})) IN ('FLORIDA', 'FL') THEN 'FL' 
        WHEN TRIM(UPPER({{ state }})) IN ('GEORGIA', 'GA') THEN 'GA' 
        WHEN TRIM(UPPER({{ state }})) IN ('HAWAII', 'HI') THEN 'HI' 
        WHEN TRIM(UPPER({{ state }})) IN ('IDAHO', 'ID') THEN 'ID' 
        WHEN TRIM(UPPER({{ state }})) IN ('ILLINOIS', 'IL') THEN 'IL' 
        WHEN TRIM(UPPER({{ state }})) IN ('INDIANA', 'IN') THEN 'IN' 
        WHEN TRIM(UPPER({{ state }})) IN ('IOWA', 'IA') THEN 'IA' 
        WHEN TRIM(UPPER({{ state }})) IN ('KANSAS', 'KS') THEN 'KS' 
        WHEN TRIM(UPPER({{ state }})) IN ('KENTUCKY', 'KY') THEN 'KY' 
        WHEN TRIM(UPPER({{ state }})) IN ('LOUISIANA', 'LA') THEN 'LA' 
        WHEN TRIM(UPPER({{ state }})) IN ('MAINE', 'ME') THEN 'ME' 
        WHEN TRIM(UPPER({{ state }})) IN ('MARYLAND', 'MD') THEN 'MD' 
        WHEN TRIM(UPPER({{ state }})) IN ('MASSACHUSETTS', 'MA') THEN 'MA' 
        WHEN TRIM(UPPER({{ state }})) IN ('MICHIGAN', 'MI') THEN 'MI' 
        WHEN TRIM(UPPER({{ state }})) IN ('MINNESOTA', 'MN') THEN 'MN' 
        WHEN TRIM(UPPER({{ state }})) IN ('MISSIPPI', 'MS') THEN 'MS' 
        WHEN TRIM(UPPER({{ state }})) IN ('MISSOURI', 'MO') THEN 'MO' 
        WHEN TRIM(UPPER({{ state }})) IN ('MONTANA', 'MT') THEN 'MT' 
        WHEN TRIM(UPPER({{ state }})) IN ('NEBRASKA', 'NE') THEN 'NE' 
        WHEN TRIM(UPPER({{ state }})) IN ('NEVADA', 'NV') THEN 'NV' 
        WHEN TRIM(UPPER({{ state }})) IN ('NEW HAMPSHIRE', 'NH') THEN 'NH' 
        WHEN TRIM(UPPER({{ state }})) IN ('NEW JERSEY', 'NJ') THEN 'NJ' 
        WHEN TRIM(UPPER({{ state }})) IN ('NEW MEXICO', 'NM') THEN 'NM' 
        WHEN TRIM(UPPER({{ state }})) IN ('NEW YORK', 'NY') THEN 'NY' 
        WHEN TRIM(UPPER({{ state }})) IN ('NORTH CAROLINA', 'NC') THEN 'NC' 
        WHEN TRIM(UPPER({{ state }})) IN ('NORTH DAKOTA', 'ND') THEN 'ND' 
        WHEN TRIM(UPPER({{ state }})) IN ('OHIO', 'OH') THEN 'OH' 
        WHEN TRIM(UPPER({{ state }})) IN ('OKLAHOMA', 'OK') THEN 'OK' 
        WHEN TRIM(UPPER({{ state }})) IN ('OREGON', 'OR') THEN 'OR' 
        WHEN TRIM(UPPER({{ state }})) IN ('PENNSYLVANIA', 'PA') THEN 'PA' 
        WHEN TRIM(UPPER({{ state }})) IN ('RHODE ISLAND', 'RI') THEN 'RI' 
        WHEN TRIM(UPPER({{ state }})) IN ('SOUTH CAROLINA', 'SC') THEN 'SC' 
        WHEN TRIM(UPPER({{ state }})) IN ('SOUTH DAKOTA', 'SD') THEN 'SD' 
        WHEN TRIM(UPPER({{ state }})) IN ('TENNESSEE', 'TN') THEN 'TN' 
        WHEN TRIM(UPPER({{ state }})) IN ('TEXAS', 'TX') THEN 'TX' 
        WHEN TRIM(UPPER({{ state }})) IN ('UTAH', 'UT') THEN 'UT' 
        WHEN TRIM(UPPER({{ state }})) IN ('VERMONT', 'VT') THEN 'VT' 
        WHEN TRIM(UPPER({{ state }})) IN ('VIRGINIA', 'VA') THEN 'VA' 
        WHEN TRIM(UPPER({{ state }})) IN ('WASHINGTON', 'WA') THEN 'WA' 
        WHEN TRIM(UPPER({{ state }})) IN ('WEST VIRGINIA', 'WV') THEN 'WV' 
        WHEN TRIM(UPPER({{ state }})) IN ('WISCONSIN', 'WI') THEN 'WI' 
        WHEN TRIM(UPPER({{ state }})) IN ('WYOMING', 'WY') THEN 'WY' 
        WHEN TRIM(UPPER({{ state }})) IN ('ALBERTA', 'AB') THEN 'AB' 
        WHEN TRIM(UPPER({{ state }})) IN ('BRITISH COLUMBIA', 'BC') THEN 'BC' 
        WHEN TRIM(UPPER({{ state }})) IN ('MANITOBA', 'MB') THEN 'MB' 
        WHEN TRIM(UPPER({{ state }})) IN ('NEW BRUNSWICK', 'NB') THEN 'NB' 
        WHEN TRIM(UPPER({{ state }})) IN ('NEWFOUNDLAND AND LABRADOR', 'NL') THEN 'NL' 
        WHEN TRIM(UPPER({{ state }})) IN ('NORTHWEST TERRITORIES', 'NT') THEN 'NT' 
        WHEN TRIM(UPPER({{ state }})) IN ('NOVA SCOTIA', 'NS') THEN 'NS' 
        WHEN TRIM(UPPER({{ state }})) IN ('NUNAVUT', 'NU') THEN 'NU' 
        WHEN TRIM(UPPER({{ state }})) IN ('ONTARIO', 'ON') THEN 'ON' 
        WHEN TRIM(UPPER({{ state }})) IN ('PRINCE EDWARD ISLAND', 'PE') THEN 'PE' 
        WHEN TRIM(UPPER({{ state }})) IN ('QUEBEC', 'QC') THEN 'QC' 
        WHEN TRIM(UPPER({{ state }})) IN ('SASKATCHEWAN', 'SK') THEN 'SK'
        WHEN TRIM(UPPER({{ state }})) IN ('YUKON TERRITORY', 'YT') THEN 'YT' 
            ELSE NULL
    END

{%- endmacro %}
